#!/bin/bash
set -e

BRANCH="stage"
IMAGE_TAG="614788684359.dkr.ecr.ap-southeast-2.amazonaws.com/stage-web-api:latest"
STAGE_SERVICE="stage-web-api"
STAGE_CLUSTER="stage-cluster"
STAGE_TASK="stage-web-api"


cd /home/nestjs/stage/web_api

git checkout $BRANCH

git pull origin $BRANCH

aws ssm get-parameters-by-path --path /nestjs/stage/web-api/ --query 'Parameters[].[Name,Value]' --with-decryption --output text | sed -E 's#/nestjs/stage/web-api/([^[:space:]]*)[[:space:]]*#\1=#g' > .env

docker build --force-rm -t $IMAGE_TAG .

aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 614788684359.dkr.ecr.ap-southeast-2.amazonaws.com

docker push $IMAGE_TAG

aws ecs update-service --cluster ${STAGE_CLUSTER} --service ${STAGE_SERVICE} --task-definition ${STAGE_TASK} --force-new-deployment
 
docker image prune -f
 
docker rmi $IMAGE_TAG

